#ifndef BZM_REGISTERS_H
#define BZM_REGISTERS_H

#include <stddef.h>
#include <stdint.h>

/*
 * Bonanza control/notch-register offsets used by the production telemetry
 * path.  Keep these names separate from the engine-register address space:
 * both spaces reuse several byte offsets.
 */
enum
{
    BZM_LOCAL_REG_RESULT_STATUS_CONTROL = 0x00,
    BZM_LOCAL_REG_UART_TDM_CONTROL = 0x07,
    BZM_LOCAL_REG_SLOW_CLOCK_DIVIDER = 0x08,
    BZM_LOCAL_REG_TDM_DELAY = 0x09,
    BZM_LOCAL_REG_UART_TX = 0x0a,
    BZM_LOCAL_REG_ASIC_ID = 0x0b,

    BZM_LOCAL_REG_PLL0_CONTROL = 0x0f,
    BZM_LOCAL_REG_PLL0_POSTDIV = 0x10,
    BZM_LOCAL_REG_PLL0_FBDIV = 0x11,
    BZM_LOCAL_REG_PLL0_ENABLE = 0x12,
    BZM_LOCAL_REG_PLL0_MISC = 0x13,
    BZM_LOCAL_REG_ENGINE_SOFT_RESET = 0x16,
    BZM_LOCAL_REG_PLL1_CONTROL = 0x19,
    BZM_LOCAL_REG_PLL1_POSTDIV = 0x1a,
    BZM_LOCAL_REG_PLL1_FBDIV = 0x1b,
    BZM_LOCAL_REG_PLL1_ENABLE = 0x1c,
    BZM_LOCAL_REG_PLL1_MISC = 0x1d,

    BZM_LOCAL_REG_SENSOR_TDM_GAP_COUNT = 0x2d,
    BZM_LOCAL_REG_DTS_RESET_POWERDOWN = 0x2e,
    BZM_LOCAL_REG_DTS_CONFIG = 0x2f,
    BZM_LOCAL_REG_TEMPERATURE_TUNE_CODE = 0x30,
    BZM_LOCAL_REG_THERMAL_TRIP_STATUS = 0x31,
    BZM_LOCAL_REG_TEMPERATURE_CODE_STATUS = 0x32,
    BZM_LOCAL_REG_THERMAL_SAR_COUNT_LOAD = 0x34,
    BZM_LOCAL_REG_THERMAL_SAR_STATE_RESET = 0x35,
    BZM_LOCAL_REG_SENSOR_THRESHOLD_COUNT = 0x3c,
    BZM_LOCAL_REG_SENSOR_CLOCK_DIVIDER = 0x3d,
    BZM_LOCAL_REG_VSENSOR_RESET_POWERDOWN = 0x3e,
    BZM_LOCAL_REG_VSENSOR_CONFIG = 0x3f,
    BZM_LOCAL_REG_VSENSOR_CONTROL = 0x40,
    BZM_LOCAL_REG_VSENSOR_CH0_STATUS = 0x41,
    BZM_LOCAL_REG_VSENSOR_MISC = 0x42,
    BZM_LOCAL_REG_VSENSOR_DFT = 0x43,
    BZM_LOCAL_REG_VSENSOR_CH1_CH2_STATUS = 0x44,
    BZM_LOCAL_REG_BANDGAP = 0x45,
    BZM_LOCAL_REG_IO_PEPS_DRIVE_STRENGTH = 0x51,

    BZM_LOCAL_REG_DLL0_CONTROL_0 = 0x54,
    BZM_LOCAL_REG_DLL0_CONTROL_5 = 0x59,
    BZM_LOCAL_REG_DLL0_LOCK_0 = 0x5a,
    BZM_LOCAL_REG_DLL0_LOCK_1 = 0x5b,
    BZM_LOCAL_REG_DLL1_CONTROL_0 = 0x5c,
    BZM_LOCAL_REG_DLL1_CONTROL_5 = 0x61,
    BZM_LOCAL_REG_DLL1_LOCK_0 = 0x62,
    BZM_LOCAL_REG_DLL1_LOCK_1 = 0x63,
};

enum
{
    BZM_TEMPERATURE_CODE_MASK = 0x0fff,
    BZM_TEMPERATURE_SENSOR_FAULT_MASK = 1u << 12,
    BZM_THERMAL_TRIP_MASK = 1u << 0,
    BZM_VOLTAGE_CODE_MASK = 0x3fff,
    BZM_VOLTAGE_CH0_SHUTDOWN_MASK = 1u << 31,
    BZM_VOLTAGE_SENSOR_FAULT_MASK = 1u << 30,
    BZM_VOLTAGE_CH1_SHUTDOWN_MASK = 1u << 29,
};

/* All currently documented control-register reads are 32-bit little-endian. */
#define BZM_CONTROL_REGISTER_WIDTH 4U

const char * bzm_local_register_name(uint8_t offset);
size_t bzm_local_register_width(uint8_t offset);

#endif // BZM_REGISTERS_H
